name: Push to deployment repo (Vercel trigger)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare output directory
        run: sh ./build.sh

      - name: Push to deployment repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: bsu0404
          destination-repository-name: mbtid
          user-email: ${{ secrets.EMAIL }}
          commit-message: "deploy: ${{ github.event.head_commit.message }}"
          target-branch: main

      - name: Confirm destination directory
        run: echo $DESTINATION_CLONED_DIRECTORY
